# Generated by Django 3.2.4 on 2021-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=2, verbose_name='size')),
            ],
        ),
    ]
