# Generated by Django 3.2.4 on 2021-07-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
            ],
            options={
                'verbose_name': 'The Product',
                'verbose_name_plural': 'All the Products',
            },
        ),
    ]
