# Generated by Django 3.2.4 on 2021-07-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'All Products'},
        ),
    ]
