# Generated by Django 3.2.4 on 2021-07-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_front', '0002_auto_20210720_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
