# Generated by Django 3.2.4 on 2021-09-01 18:33

from django.db import migrations, models
import django.utils.timezone
import store_front.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_front', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=store_front.models.upload_location),
            preserve_default=False,
        ),
    ]
